/* Reference-led landing UI. Existing auth handlers, dashboard and backend stay intact. */
window.AdimaLanding = (() => {
const paths={
idea:'<path d="M9 18h6m-5 3h4M8.5 14.5a7 7 0 1 1 7 0C14.5 15.3 15 17 15 17H9s.5-1.7-.5-2.5Z"/>',
script:'<path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6m-6 4h6"/>',
image:'<rect x="3" y="4" width="18" height="16" rx="3"/><circle cx="8" cy="9" r="1.5"/><path d="m4 18 6-6 4 4 3-3 4 5"/>',
video:'<rect x="3" y="6" width="12" height="12" rx="3"/><path d="m15 10 6-4v12l-6-4Z"/>',
box:'<path d="m12 2 9 5v10l-9 5-9-5V7Zm0 10 9-5M3 7l9 5v10M7.5 4.5l9 5"/>',
play:'<path d="m9 5 11 7-11 7Z"/>',
sound:'<rect x="9" y="2" width="6" height="13" rx="3"/><path d="M6 10v2a6 6 0 0 0 12 0v-2m-6 8v4m-4 0h8"/>',
scene:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 10h18M8 4l-3 6m9-6-3 6m9-6-3 6"/>',
sparkle:'<path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z"/>',
bolt:'<path d="m13 2-9 12h7l-1 8 10-13h-7Z"/>',
heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>'};
function icon(name,cls=''){return '<svg class="al-icon '+cls+'" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(paths[name]||paths.sparkle)+'</svg>';}
function mark(){return '<svg class="al-mark" viewBox="0 0 40 40" aria-hidden="true"><defs><linearGradient id="al-brand-gradient" x1="0" y1="1" x2="1" y2="0"><stop stop-color="#00d6ed"/><stop offset=".5" stop-color="#63a6ff"/><stop offset="1" stop-color="#bc8cff"/></linearGradient></defs><path d="M20 1c4 13 6 15 19 19-13 4-15 6-19 19C16 26 14 24 1 20 14 16 16 14 20 1Z" fill="url(#al-brand-gradient)" stroke="white"/></svg>';}
function tile(name,label,tone){return '<div class="al-flow-item"><span class="al-tile '+tone+'">'+icon(name)+'</span><strong>'+label+'</strong></div>';}
function feature(name,title,subtitle,tone){return '<button class="al-feature" data-al-start><span class="al-small-tile '+tone+'">'+icon(name)+'</span><span><strong>'+title+'</strong><span class="al-feature-subtitle">'+subtitle+'</span></span></button>';}
function render(){return `
<div id="landingView" class="al-page al-new-page">
<a class="al-skip" href="#al-main">Skip to content</a>
<div class="al-container">
<nav class="al-nav" aria-label="Main navigation">
<a class="al-brand" href="#al-home" aria-label="Adima AI home">${mark()}<span>Adima AI</span></a>
<button class="al-menu" id="alMenuButton" aria-expanded="false" aria-controls="alNavLinks" aria-label="Open navigation">${icon('box')}</button>
<div class="al-nav-links" id="alNavLinks"><a href="#al-product">Product</a><a href="#al-how">How it works</a><a href="#al-pricing">Pricing</a><button class="al-text-button" id="navLoginBtn">Log in</button><button class="al-button al-primary" id="navSignupBtn">Start creating ${icon('arrow')}</button></div>
</nav>
<main id="al-main">
<header class="al-hero al-hero-card" id="al-home">
<div class="al-hero-copy"><span class="al-badge">${icon('sparkle')} Your AI production partner</span><h1>Create smarter<br>with AI</h1><p>From a rough idea to a production-ready plan, Adima gives creators a clearer way to make video.</p><div class="al-actions"><button class="al-button al-primary" id="heroTryBtn">Start creating free ${icon('arrow')}</button><button class="al-button al-secondary" id="heroLaunchBtn">${icon('play')} See how it works</button></div><p class="al-hero-proof">No credit card required · Built for ambitious creators</p></div>
<div class="al-hero-preview" aria-label="Preview of an AI video project" role="img"><div class="al-preview-top"><span>${icon('sparkle')} Adima workspace</span><span class="al-preview-dot"></span></div><div class="al-preview-scene"><span class="al-preview-label">PROJECT BRIEF</span><h2>How AI changes<br>the way we create</h2><button aria-label="Play project preview">${icon('play')}</button><span class="al-preview-time">00:60</span></div><div class="al-preview-steps"><span class="is-active">Idea</span><span>Script</span><span>Scenes</span><span>Ready</span></div></div>
</header>
<section class="al-intro" id="al-product" aria-labelledby="al-intro-title"><div class="al-eyebrow">ONE SPACE. EVERY STEP.</div><div class="al-section-lead"><h2 id="al-intro-title">Create smarter with AI</h2><p>Adima turns your first thought into a practical creative system—without the blank page, scattered tabs or production guesswork.</p></div><div class="al-intro-tiles"><article>${icon('idea')}<h3>Start with a spark</h3><p>Describe what you want to make in your own words.</p></article><article>${icon('sparkle')}<h3>Get creative direction</h3><p>Shape the story, voice and visual angle together.</p></article><article>${icon('box')}<h3>Leave with a plan</h3><p>Take clear assets into your next production step.</p></article></div></section>
<section class="al-panel al-video-production" aria-labelledby="al-video-title"><div class="al-section-copy"><span class="al-eyebrow">YOUR WORKFLOW, UNBLOCKED</span><h2 id="al-video-title">One-Click AI Video Production</h2><p>Move from a single idea through scripting, scenes and delivery in one focused creative flow.</p><button class="al-text-button" data-al-start>Build your first project ${icon('arrow')}</button></div><div class="al-workflow-preview" aria-label="Video production workflow preview"><div class="al-workflow-head"><span>New project</span><span>60 sec · Explainer</span></div><div class="al-workflow-row">${tile('idea','Brief','al-blue')}${icon('arrow','al-connector')}${tile('script','Script','al-purple')}${icon('arrow','al-connector')}${tile('scene','Scenes','al-cyan')}${icon('arrow','al-connector')}${tile('video','Production','al-orange')}</div></div></section>
<section class="al-agent-new" id="al-agent" aria-labelledby="al-agent-title"><div class="al-agent-new-copy"><span class="al-eyebrow">A COLLABORATOR THAT KEEPS UP</span><h2 id="al-agent-title">Meet Your AI Video Production Agent</h2><p>Ask for a hook, a stronger scene or a fresh angle. Adima works alongside your process and keeps the whole production moving.</p><button class="al-button al-primary" id="ctaGetStartedBtn">Chat with Adima ${icon('arrow')}</button></div><div class="al-agent-product"><div class="al-agent-product-head"><strong>${icon('sparkle')} Adima</strong><span>AI Producer</span></div><div class="al-message al-message-user">I need a 60-second launch video for a new coffee brand.</div><div class="al-message al-message-ai"><span>${icon('sparkle')}</span><p>Great. I’ve mapped a warm, sensory story with an opening hook, 8 scenes and a final call to action.</p></div><div class="al-agent-output"><span>Production plan ready</span><strong>8 scenes · Script · Visual prompts</strong><button data-al-start aria-label="Open production plan">${icon('arrow')}</button></div></div></section>
<section class="al-scenes" aria-labelledby="al-scenes-title"><div class="al-section-lead"><span class="al-eyebrow">FROM A SINGLE SPARK</span><h2 id="al-scenes-title">From 60 Seconds → 8 Production Scenes</h2><p>See the full story before you enter the edit. Each scene gets a purpose, a visual and a natural next step.</p></div><div class="al-scene-grid">${['The first pour','A quiet morning','The origin story','The perfect roast','A shared pause','Make it yours','The daily ritual','One last sip'].map((title,i)=>`<article class="al-scene-card"><span>0${i+1}</span><div class="al-scene-art al-scene-${i+1}"></div><h3>${title}</h3><p>${i===0?'Open with a sensory hook.':'A purposeful moment in the story.'}</p></article>`).join('')}</div></section>
<section class="al-prompt-section" aria-labelledby="al-prompt-title"><div><span class="al-eyebrow">MAKE THE VAGUE USEFUL</span><h2 id="al-prompt-title">Turn Simple Ideas Into Production-Ready Prompts</h2><p>Adima adds structure and creative context while you stay in control of the idea.</p></div><div class="al-prompt-ui"><div class="al-prompt-before"><span>YOUR IDEA</span><p>“A video about a coffee brand.”</p></div><div class="al-prompt-arrow">${icon('arrow')}</div><div class="al-prompt-after"><span>ADIMA PROMPT</span><p>Create a warm 60-second brand film about a coffee ritual, with intimate morning visuals, a calm voiceover and a closing invitation to slow down.</p><div><em>Audience: mindful coffee drinkers</em><em>Tone: warm, cinematic</em></div></div></div></section>
<section class="al-delivery" aria-labelledby="al-delivery-title"><div class="al-section-lead"><span class="al-eyebrow">EVERYTHING YOU NEED NEXT</span><h2 id="al-delivery-title">One Idea → Complete Production</h2><p>Use the output as your practical launchpad—not just another chat response.</p></div><div class="al-delivery-grid">${[['script','A focused script','A clear narrative from hook to close.','al-purple'],['scene','Scene-by-scene plan','Eight purposeful moments ready to make.','al-cyan'],['image','Visual prompts','Direction for every key frame.','al-orange'],['sound','Voiceover copy','Words that carry the story.','al-pink'],['video','Production checklist','Know what to create and capture next.','al-blue'],['box','Exportable package','Keep your work in a usable format.','al-green']].map(([i,t,p,c])=>`<article>${'<span class="al-small-tile '+c+'">'+icon(i)+'</span>'}<h3>${t}</h3><p>${p}</p></article>`).join('')}</div></section>
<section class="al-how-new" id="al-how" aria-labelledby="al-how-title"><div class="al-section-lead"><span class="al-eyebrow">SIMPLE BY DESIGN</span><h2 id="al-how-title">How It Works</h2></div><ol><li><span>01</span><h3>Share the idea</h3><p>Start with a topic, goal or half-formed thought.</p></li><li><span>02</span><h3>Shape it with Adima</h3><p>Explore direction, structure and scenes together.</p></li><li><span>03</span><h3>Make the work real</h3><p>Export your plan and move into production.</p></li></ol></section>
<section class="al-core" aria-labelledby="al-core-title"><div class="al-section-lead"><span class="al-eyebrow">MORE THAN A PROMPT BOX</span><h2 id="al-core-title">Core Features</h2></div><div class="al-core-grid">${feature('script','Script builder','Create a strong story structure.','al-purple')}${feature('scene','Scene planner','Break the story into clear beats.','al-cyan')}${feature('image','Visual direction','Turn words into frame-ready prompts.','al-orange')}${feature('sound','Voice and tone','Find language that sounds like you.','al-pink')}</div></section>
<section class="al-creators" aria-labelledby="al-creators-title"><div><span class="al-eyebrow">FOR THE PEOPLE MAKING WHAT’S NEXT</span><h2 id="al-creators-title">Built for Creators</h2><p>Whether you are launching a brand, telling stories for clients or building an audience, Adima gives your ideas a dependable production partner.</p></div><ul><li>${icon('play')} Video creators</li><li>${icon('heart')} Creative teams</li><li>${icon('sparkle')} Founders & brands</li></ul></section>
<section class="al-pricing" id="al-pricing" aria-labelledby="al-pricing-title"><div class="al-section-lead"><span class="al-eyebrow">START SMALL. GROW FREELY.</span><h2 id="al-pricing-title">Plans for every creative pace</h2></div><div class="al-price-grid"><article><h3>Explore</h3><p>For your first ideas.</p><strong>Free</strong><ul><li>AI creative chat</li><li>Starter production plans</li><li>Text exports</li></ul><button class="al-button al-secondary" data-al-start>Get started</button></article><article class="al-price-featured"><span>Most popular</span><h3>Creator</h3><p>For more ambitious output.</p><strong>Coming soon</strong><ul><li>Expanded creative workflows</li><li>More project space</li><li>Priority features</li></ul><button class="al-button al-primary" data-al-start>Join the waitlist</button></article></div></section>
<section class="al-faq" aria-labelledby="al-faq-title"><div class="al-section-lead"><span class="al-eyebrow">QUESTIONS, ANSWERED</span><h2 id="al-faq-title">Frequently asked questions</h2></div><div class="al-faq-list">${[['What does Adima create today?','Adima currently helps you generate and refine text-based creative work, including scripts, scene ideas, visual prompts and exportable plans.'],['Does Adima make finished videos?','The production workflow previews show how a complete process can be organized. Video, voice and image rendering are not connected in the current workspace.'],['Can I use my own creative direction?','Yes. Start with your own idea and guide the tone, audience, format and details as you refine the result.'],['How do I get started?','Choose any Start creating button to open the existing sign-in flow, then continue to the workspace.']].map(([q,a],i)=>`<article class="al-faq-item"><h3><button class="al-faq-question" aria-expanded="${i===0?'true':'false'}" aria-controls="al-faq-answer-${i}" id="al-faq-question-${i}">${q}<span aria-hidden="true">+</span></button></h3><div class="al-faq-answer" id="al-faq-answer-${i}" role="region" aria-labelledby="al-faq-question-${i}" ${i===0?'':'hidden'}><p>${a}</p></div></article>`).join('')}</div></section>
<section class="al-final-cta" aria-labelledby="al-final-title"><span class="al-eyebrow">YOUR NEXT IDEA STARTS HERE</span><h2 id="al-final-title">Make space for better creative work.</h2><p>Bring the first thought. Leave with a plan.</p><button class="al-button al-primary" data-al-start>Start creating with Adima ${icon('arrow')}</button></section>
</main><footer class="al-footer"><a class="al-brand" href="#al-home">${mark()}<span>Adima AI</span></a><p>One idea. A clearer path to production.</p><div><a href="#al-core">Features</a><a href="#al-pricing">Pricing</a><a href="#al-home">Back to top ↑</a></div><small>© ${new Date().getFullYear()} Adima AI</small></footer>
</div>
<dialog class="al-demo" id="alDemo" aria-labelledby="al-demo-title"><button class="al-dialog-close" id="alDemoClose" aria-label="Close demo">×</button><span class="al-badge">PRODUCT WALKTHROUGH</span><h2 id="al-demo-title">A little idea. <br>A great starting point.</h2><p class="al-demo-note">Illustrative example — not a live generation.</p><div class="al-demo-prompt"><strong>Your idea</strong><p>Write a short video script about AI for beginners.</p></div><div class="al-demo-output"><strong>A possible starting point</strong><p><b>Hook:</b> You’ve probably used AI today without noticing.</p><p><b>Story:</b> From suggested songs to voice assistants, AI looks for patterns to help us with everyday tasks.</p><p><b>Close:</b> Which everyday AI tool do you use most?</p></div><p>Sign in to generate your own text, refine it and export it from the existing Adima workspace.</p><button class="al-button al-primary" id="alDemoStart">Try your own idea ${icon('arrow')}</button></dialog>
</div>`;}
function init(){
const landing=document.getElementById('landingView'),modal=document.getElementById('authModal'),demo=document.getElementById('alDemo'),menu=document.getElementById('alMenuButton'),links=document.getElementById('alNavLinks');
let returnFocus=null,previousOverflow='';
function closeMenu(){menu.setAttribute('aria-expanded','false');links.classList.remove('is-open');}
function start(){closeMenu();openAuthModal();}
['navLoginBtn','navSignupBtn','heroTryBtn','ctaGetStartedBtn'].forEach(id=>document.getElementById(id).onclick=start);
landing.querySelectorAll('[data-al-start]').forEach(btn=>btn.onclick=start);
landing.querySelectorAll('.al-faq-question').forEach(button=>button.onclick=()=>{const answer=document.getElementById(button.getAttribute('aria-controls'));const open=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!open));answer.hidden=open;});
menu.onclick=()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));links.classList.toggle('is-open',open);};
links.querySelectorAll('a').forEach(a=>a.onclick=closeMenu);
document.getElementById('heroLaunchBtn').onclick=()=>{previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';demo.showModal();};
demo.addEventListener('close',()=>{if(modal.style.display!=='flex')document.body.style.overflow=previousOverflow;});
document.getElementById('alDemoClose').onclick=()=>demo.close();
demo.addEventListener('click',e=>{if(e.target===demo){const r=demo.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)demo.close();}});
document.getElementById('alDemoStart').onclick=()=>{demo.close();start();};
document.getElementById('authModalClose').onclick=closeAuthModal;
document.getElementById('authModalOverlay').onclick=closeAuthModal;
document.getElementById('togglePasswordBtn').onclick=()=>{const pwd=document.getElementById('authPassword');const show=pwd.type==='password';pwd.type=show?'text':'password';document.getElementById('togglePasswordBtn').setAttribute('aria-label',show?'Hide password':'Show password');};
const authCard=modal.querySelector('.glass-card');
authCard.setAttribute('role','dialog');authCard.setAttribute('aria-modal','true');authCard.setAttribute('aria-labelledby','al-auth-title');authCard.tabIndex=-1;authCard.querySelector('h2').id='al-auth-title';
document.getElementById('authModalClose').setAttribute('aria-label','Close sign-in');document.getElementById('togglePasswordBtn').setAttribute('aria-label','Show password');
document.getElementById('authEmail').autocomplete='email';document.getElementById('authPassword').autocomplete='current-password';
document.getElementById('authError').setAttribute('role','alert');document.getElementById('authSuccess').setAttribute('role','status');
let authOpen=false;
new MutationObserver(()=>{const open=modal.style.display==='flex';if(open===authOpen)return;authOpen=open;if(open){returnFocus=document.activeElement;landing.inert=true;document.getElementById('googleSignInBtn').focus();}else{landing.inert=false;if(returnFocus&&landing.style.display!=='none')returnFocus.focus();}}).observe(modal,{attributes:true,attributeFilter:['style']});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();if(authOpen)closeAuthModal();}if(authOpen&&e.key==='Tab'){const list=[...authCard.querySelectorAll('button,input,a[href],[tabindex="0"]')].filter(el=>!el.disabled&&el.getClientRects().length);const first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
}
return {render,init};
})();
